server:
  port: 0

spring:
  datasource:
    initialization-mode: always
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5435/warehouse
    username: warehouse
    password: warehouse
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true
        alphanumeric-ids:
          enabled: true

resilience4j.circuitbreaker:
  configs:
    default:
      slidingWindowSize: 50
      failureRateThreshold: 50
instances:
  order:
    slidingWindowSize: 10
    waitDurationInOpenState: 10000 # 10 секунд в миллисекундах
    permittedNumberOfCallsInHalfOpenState: 3
    slidingWindowType: COUNT_BASED
    minimumNumberOfCalls: 5
    automaticTransitionFromOpenToHalfOpenEnabled: true
